services:
  criclabs-code-challenge:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app  # Mount local files to /app in the container
      - /app/node_modules  # Prevent overwriting node_modules with local volume
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@criclabs-db:5432/criclabs
      - CHOKIDAR_USEPOLLING=true  # Fix for file change detection
      - WATCHPACK_POLLING=true     # Alternative fix for hot reload issues
    depends_on:
      - criclabs-db
    command: >
      sh -c "yarn install && npx prisma generate && yarn dev"

  criclabs-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: criclabs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: